### PR TITLE
removing a removePopup() method not used

### PR DESCRIPTION
**Pull request by CarlyLanglois**
popups are removed via the updatePopups() method

### CODE REVIEW

**Comment by bartvde** [comment]
hmm does this make sense? I think we would still want a way for people to programatically remove a popup? cc @theduckylittle

**Comment by CarlyLanglois** [comment]
oh good point. but if the map component accomplishes removing a popup w/o this method, would it make sense to just include a remove function inside of whatever app needs it?

**Comment by bartvde** [comment]
it is true that popups can still be closed by calling the close method on the popup itself

I'm not sure if we need to have 2 ways, I'll let @theduckylittle decide since he wrote the original popup code

**Comment by theduckylittle** [comment]
Please don't remove potentially useful API calls. :)

`updatePopups` does the real work but we should have an exposed method for removing a popup by ID.  The only real flaw here is that we should be returning the popup ID in addPopup so it's easier to reference.

**Comment by CarlyLanglois** [comment]
ok, thanks for the notes. I'll close this then

**Pull request closed without merging**
