### PR TITLE
add map name action updates map name in state

### PR DESCRIPTION
**Pull request by CarlyLanglois**
Map name in state tree can be changed with a redux action. 
Basic App contains an input component to demonstrate this action. Needs styling if the component will stay in this app.

### CODE REVIEW

**Comment by CarlyLanglois** [comment]
yeah good point. I'll change the names. 
I also just realized I didn't think about writing a test for this so I'll do that too.

**Comment by CarlyLanglois** [comment]
@theduckylittle You want me to also just get rid of the name-change demo in the example app?

**Comment by theduckylittle** [comment]
Let's leave it in for now and as we may end up having a follow up discussion on which features to demo where.

**Comment by theduckylittle** [comment]
I tweaked some of the CSS in the basic app so that it wasn't overlapping on narrow screens. Otherwise it all looks good, thanks!

**Pull request merged**
