### PR TITLE
Upgrade ol and ol-mapbox-style

### PR DESCRIPTION
**Pull request by bartvde**
SDK-769

The labels are a bit crowded though, is that to be expected @ahocevar ? Is it because the labels are in multiple layers, or is the new collission detection supported for that use case as well?

selection_428

### CODE REVIEW

**Comment by ahocevar** [comment]
OpenLayers decluttering is on the level of OpenLayers layer instances. You're also sacrificing performance by having the same source rendered by multiple layers. I'd recommend to use `apply` instead of `applyStyle`, which will optimize OpenLayers layer instance creation.

We could also add mapbox-style source and layer ids to the OpenLayers layer instances to make them easier to work with after creation.

**Comment by bartvde** [comment]
cc-ing @theduckylittle since he might remember some of these early design decisions

**Comment by bartvde** [comment]
@ahocevar was the previous labelgun based decluttering not on a per layer basis? Because I can't recall we saw this back then.

**Comment by theduckylittle** [comment]
The reason for using applyStyle instead of style was so that we had finer control over individual layer changes. It allows us to do more fine-grained diffs between previous and new layer states.

**Comment by bartvde** [comment]
@ahocevar I just confirmed, but we actually have a single vector tile layer since we group layers by source

**Pull request merged**
