### PR TITLE
Infopop attr filter

### PR DESCRIPTION
**Pull request by CarlyLanglois**

### CODE REVIEW

**Comment by bartvde** [comment]
So if I understand the PR correctly, in addition to what we have for popupInfo:

 * string based template with [foo] for attribute foo
 * '#AllAttributes' to show all attributes

we are adding a third mode with an array of attributes to show right?

**Comment by bartvde** [comment]
No the deletion breaks the basic example. Compare before and after:
selection_248
selection_249

**Comment by CarlyLanglois** [comment]
thanks Bart. I've put the block back in that handles this type of popupInfo and changed where to use getGeometryName()

**Comment by bartvde** [comment]
next step would be to document all the options somewhere but this can be done in a new PR

**Pull request merged**
