### PR TITLE
prevent map component  from crashing

### PR DESCRIPTION
**Pull request by hishamkaram**
prevent map component from crashing if the sdk failed to export map as image 
error sample: `DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

### CODE REVIEW

**Comment by hishamkaram** [comment]
@bartvde  done

**Comment by bartvde** [comment]
I'm fixing the Jenkins failure in #935 so once that is merged, if you rebase this one it should pass. Btw, I don't think it's in our eslint config, but it would be good to add the missing ```;``` as well.

**Comment by bartvde** [comment]
if you run ```git pull --rebase upstream master``` followed by a force push to your branch it should pass

**Comment by hishamkaram** [comment]
@bartvde done

**Pull request merged**
