### PR TITLE
Use dotenv for Mapbox API key

### PR DESCRIPTION
**Pull request by bartvde**
SDK-795

### CODE REVIEW

**Comment by bartvde** [comment]
This came up in #760

**Comment by bartvde** [comment]
We currently don't build any of the examples that require a mapbox key but I will verify anyway

**Comment by bartvde** [comment]
@theduckylittle I verified it will work in the example production builds if we ever need that.

selection_434

I'll add it to that webpack config as well here.

**Comment by theduckylittle** [comment]
Cool! My hope was that we could get a key on the examples server to actually let this one work now! Thanks!

**Comment by bartvde** [comment]
yes that is my hope also still ;-)

**Pull request merged**
